language: scala
scala:
- 2.11.2
cache:
  directories:
  - $HOME/.m2
before_deploy:
- mvn assembly:assembly -DdescriptorId=jar-with-dependencies
deploy:
  provider: releases
  api_key:
    secure: P2IvmQHOwa8WTGrHIdZmelCKL57pzJFEELKNzvqGVUXXa087rYogUfvISmrF9N/wdIHlB5H6h/ZRORmWvCUUat01kEV0DAzttzZgtpIKDQeK9bCl6YV1V051JVEfCze0W3YwhMapHNoKB4kflECYzwLUinl9kH0tJ30jXhEvN8F9RnXtjj/1WBOgIKNjnw+zBeBOM/ITQmxkK1PWdFuBrjFxt35TOUGLE1SgAxojYtPC5Ios3vuLTamFSEieBPOQIF4Qp+YPjmKQEylNJ/0PKXOmlC1I3ypJR3yQt1sAJnSPnQNWJQTCZZ0Liu7eU7JSPpaQUoI1SoerK58s1Q1Eqp3gUXkH50H8NIT2LAmeNQPNo7mYgk3H9YVt14TFtb9JNw1dZuwBJ2wc3RqMlrro799OaVgEvMRzbUpFXfS2COcWX1llvUIaTDDSgYgzYuXjhbgtiD57ftqBIbw14095OgK2+dIzHuMyOTk868zDKQvSDF1WPGLdq3h2xRML8waYDBLfwTFy2dYrcctskDXcy5oUomVJ5NW+4dgRIQZeIfFaDJA+grT9IIk4peCCWmSWTZ5AiY/D+31hjNSiP2mIRQmRQC3ZxoKpyfF2iuP01QLqTlpM9efMYfJ1yYgWhVtAXWn3cAttSEsKp9/hAytkRAd5de84r7SlZBgOFvyylZ8=
  file: target/QSim.jar
  skip_cleanup: true
  on:
    repo: Orga-UNQ/qsim
    tags: true
